s cycle sub                            # switch subtitle track
S cycle sub down                       # switch subtitle track backwards
a cycle audio                          # switch audio track
g script-binding modernz/visibility    # cycle modernz OSD visibility
F2 af toggle "pan=\"stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE\""  # enable 6->2 channel audio downmix
